services:
  postgres:
    image: postgres:16
    container_name: fitness_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # backend:
  #   build: .
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_USERNAME: user
  #     DB_PASSWORD: password
  #     DB_NAME: db
  #   depends_on:
  #     - "postgres"
  #   ports:
  #     - 8000:80


volumes:
  postgres-data: