"""Initial migration

Revision ID: e7dc5fb71867
Revises:
Create Date: 2025-01-12 23:01:56.020085

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "e7dc5fb71867"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
